ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_CUSTOMER_U]
(
    @P_CD_COMPANY 				NVARCHAR(10),
		@P_NO_CUST 						INT,
		@P_NM_CUST 						NVARCHAR(20),
		@P_NM_DEPT 						NVARCHAR(40),
		@P_NM_DUTY_RESP 			NVARCHAR(40),
		@P_DC_JOB							NVARCHAR(40),
		@P_NO_TEL 						NVARCHAR(20),
		@P_NO_CELPHONE 				NVARCHAR(20),
		@P_EMAIL 							NVARCHAR(50),
		@P_DC_RMK 						NVARCHAR(400),
		@P_NO_PARTNER 				INT,
		@P_ID_UPDATE 					NVARCHAR(15),
		@P_DTS_UPDATE					NVARCHAR(14)
)
AS
	SET @P_DTS_UPDATE = GETDATE();
  UPDATE WEB_RM_OJT_CUSTOMER
  SET CD_COMPANY = @P_CD_COMPANY,
		NO_CUST = @P_NO_CUST,
		NM_CUST = @P_NM_CUST,
		NM_DEPT = @P_NM_DEPT,
		NM_DUTY_RESP = @P_NM_DUTY_RESP,
		DC_JOB = @P_DC_JOB,
		NO_TEL = @P_NO_TEL,
		NO_CELPHONE = @P_NO_CELPHONE,
		EMAIL = @P_EMAIL,
		DC_RMK = @P_DC_RMK,
		NO_PARTNER = @P_NO_PARTNER,
		ID_UPDATE = @P_ID_UPDATE,
		DTS_UPDATE = @P_DTS_UPDATE
  WHERE CD_COMPANY = @P_CD_COMPANY AND NO_PARTNER = @P_NO_PARTNER AND NO_CUST = @P_NO_CUST
GO

ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_CUSTOMER_I]
(
    @P_CD_COMPANY 				NVARCHAR(10),
		@P_NO_CUST 						INT OUTPUT,
		@P_NM_CUST 						NVARCHAR(20),
		@P_NM_DEPT 						NVARCHAR(40),
		@P_NM_DUTY_RESP 			NVARCHAR(40),
		@P_DC_JOB							NVARCHAR(40),
		@P_NO_TEL 						NVARCHAR(20),
		@P_NO_CELPHONE 				NVARCHAR(20),
		@P_EMAIL 							NVARCHAR(50),
		@P_DC_RMK 						NVARCHAR(400),
		@P_NO_PARTNER 				INT,
		@P_ID_INSERT 					NVARCHAR(15),
		@P_DTS_INSERT					NVARCHAR(14)
)

AS
	BEGIN
		DECLARE
		@SEQ	INT = 0,

	SET @SEQ = (SELECT ISNULL(MAX(CONVERT(INT, NO_CUST)), 0) + 1 FROM WEB_RM_OJT_CUSTOMER WHERE CD_COMPANY = @P_CD_COMPANY AND NO_PARTNER = @P_NO_PARTNER)
	SET	@P_NO_CUST = @SEQ
	SET @P_DTS_INSERT = GETDATE();

	INSERT INTO WEB_RM_OJT_CUSTOMER(
		CD_COMPANY
		, NO_CUST
		, NM_CUST
		, NM_DEPT
		, NM_DUTY_RESP
		, DC_JOB
		, NO_TEL
		, NO_CELPHONE
		, EMAIL
		, DC_RMK
		, NO_PARTNER
		, ID_INSERT
		, DTS_INSERT
	)
	VALUES (
		@P_CD_COMPANY
		, @SEQ
		, @P_NM_CUST
		, @P_NM_DEPT
		, @P_NM_DUTY_RESP
		, @P_DC_JOB
		, @P_NO_TEL
		, @P_NO_CELPHONE
		, @P_EMAIL
		, @P_DC_RMK
		, @P_NO_PARTNER
		, @P_ID_INSERT
		, @P_DTS_INSERT
	)
GO

ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_I]
(
	@P_NO_PARTNER INT OUTPUT,
	@P_CD_COMPANY NVARCHAR(10),
	@P_LN_PARTNER NVARCHAR(50),
	@P_FG_PARTNER NVARCHAR(3),
	@P_TP_INTOVER NVARCHAR(3),
	@P_TP_TRNSITION NVARCHAR(3),
	@P_NM_PRES NVARCHAR(40),
	@P_NO_COMPANY NVARCHAR(10),
	@P_NO_CORP NVARCHAR(13),
	@P_CD_PARTNER NVARCHAR(20),
	@P_NO_TEL NVARCHAR(20),
	@P_NO_FAX NVARCHAR(20),
	@P_TP_PRIO NVARCHAR(3),
	@p_no_post1 NVARCHAR(15),
	@P_URL_PARTNER NVARCHAR(50),
	@P_EMAIL NVARCHAR(50),
	@P_DC_ADS1_H NVARCHAR(400),
	@P_DC_ADS1_D NVARCHAR(400),
	@P_TP_JOB NVARCHAR(50),
	@P_DC_MAINGOODS NVARCHAR(400),
	@P_CLS_JOB NVARCHAR(50),
	@P_CD_BANK NVARCHAR(20),
	@P_NO_PASSBOOK NVARCHAR(30),
	@P_CD_CON NVARCHAR(3),
	@P_AM_CRD_1 NUMERIC(17,4),
	@P_DC_SETTLE NVARCHAR(50),
	@P_DT_CLOSE NVARCHAR(8),
	@P_DC_RMK NVARCHAR(400),
	@P_ID_INSERT NVARCHAR(15),
	@P_DTS_INSERT NVARCHAR(14)
)

AS
	BEGIN
		DECLARE
		@SEQ	INT = 0,
		@V_ERR_MSG NVARCHAR(255) --에러메시지

  	IF ( RTRIM(ISNULL(@P_LN_PARTNER, '')) = '' )
  		BEGIN
    		SET @V_ERR_MSG = '고객명은 필수입니다.';
    		GOTO ERROR
  		END;

		SET @SEQ = (SELECT ISNULL(MAX(CONVERT(INT, NO_PARTNER)), 0) + 1 FROM WEB_RM_OJT_PARTNER WHERE CD_COMPANY = @P_CD_COMPANY)
		SET	@P_NO_PARTNER = @SEQ
		SET @P_DTS_INSERT = GETDATE();
	PRINT('================================================')
	PRINT(@SEQ)
	PRINT('================================================')
  BEGIN TRANSACTION;
		INSERT INTO WEB_RM_OJT_PARTNER(
			CD_COMPANY
			, NO_PARTNER
			, LN_PARTNER
      , FG_PARTNER
      , TP_INTOVER
      , TP_TRNSITION
      , NM_PRES
      , NO_COMPANY
      , NO_CORP
      , CD_PARTNER
      , NO_TEL
      , NO_FAX
      , TP_PRIO
      , no_post1
      , URL_PARTNER
      , EMAIL
      , DC_ADS1_H
      , DC_ADS1_D
      , TP_JOB
      , DC_MAINGOODS
      , CLS_JOB
      , CD_BANK
      , NO_PASSBOOK
      , CD_CON
      , AM_CRD_1
      , DC_SETTLE
      , DT_CLOSE
      , DC_RMK
			, ID_INSERT
			, DTS_INSERT
		)
		VALUES (
			@P_CD_COMPANY
			, @SEQ
			, @P_LN_PARTNER
      , @P_FG_PARTNER
      , @P_TP_INTOVER
      , @P_TP_TRNSITION
      , @P_NM_PRES
      , @P_NO_COMPANY
      , @P_NO_CORP
      , @P_CD_PARTNER
      , @P_NO_TEL
      , @P_NO_FAX
      , @P_TP_PRIO
      , @p_no_post1
      , @P_URL_PARTNER
      , @P_EMAIL
      , @P_DC_ADS1_H
      , @P_DC_ADS1_D
      , @P_TP_JOB
      , @P_DC_MAINGOODS
      , @P_CLS_JOB
      , @P_CD_BANK
      , @P_NO_PASSBOOK
      , @P_CD_CON
      , @P_AM_CRD_1
      , @P_DC_SETTLE
      , @P_DT_CLOSE
      , @P_DC_RMK
			, @P_ID_INSERT
			, @P_DTS_INSERT
		)

  IF ( @@ERROR <> 0 )
  BEGIN
    ROLLBACK TRANSACTION;
    RETURN;
  END

  COMMIT TRANSACTION;

  RETURN

ERROR:
  RAISERROR( @V_ERR_MSG, 16, 1 )
  RETURN

END

ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_companyCheck]
(
	@P_NO_PARTNER INT OUTPUT,
	@P_NO_COMPANY INT
)
AS
	BEGIN
		DECLARE
		@SEQ	INT = 0

	SET @SEQ = (SELECT MAX(CONVERT(INT, NO_PARTNER)) + 1 FROM WEB_RM_OJT_PARTNER WHERE NO_COMPANY = @P_NO_COMPANY)
	SET	@P_NO_PARTNER = @SEQ
	END
GO

ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_companyCheck]
(
	@SEQ INT OUTPUT,
	@P_NO_COMPANY INT,
	@P_CD_COMPANY NVARCHAR(10)
)
AS
BEGIN
	SET @SEQ = (SELECT COUNT(*) FROM WEB_RM_OJT_PARTNER WHERE CD_COMPANY = @P_CD_COMPANY AND NO_COMPANY = @P_NO_COMPANY)
END

ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_samePartner]
(
	@SEQ INT OUTPUT,
	@P_LN_PARTNER NVARCHAR(50),
	@P_CD_COMPANY NVARCHAR(10)
)
AS
BEGIN

	SET @SEQ = (SELECT COUNT(*) FROM WEB_RM_OJT_PARTNER WHERE CD_COMPANY = @P_CD_COMPANY AND LN_PARTNER = @P_LN_PARTNER)
	END

ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_U]
(
	@P_NO_PARTNER INT,
	@P_CD_COMPANY NVARCHAR(10),
	@P_LN_PARTNER NVARCHAR(50),
	@P_FG_PARTNER NVARCHAR(3),
	@P_TP_INTOVER NVARCHAR(3),
	@P_TP_TRNSITION NVARCHAR(3),
	@P_NM_PRES NVARCHAR(40),
	@P_NO_COMPANY NVARCHAR(10),
	@P_NO_CORP NVARCHAR(13),
	@P_CD_PARTNER NVARCHAR(20),
	@P_NO_TEL NVARCHAR(20),
	@P_NO_FAX NVARCHAR(20),
	@P_TP_PRIO NVARCHAR(3),
	@P_NO_POST1 NVARCHAR(15),
	@P_URL_PARTNER NVARCHAR(50),
	@P_EMAIL NVARCHAR(50),
	@P_DC_ADS1_H NVARCHAR(400),
	@P_DC_ADS1_D NVARCHAR(400),
	@P_TP_JOB NVARCHAR(50),
	@P_DC_MAINGOODS NVARCHAR(400),
	@P_CLS_JOB NVARCHAR(50),
	@P_CD_BANK NVARCHAR(20),
	@P_NO_PASSBOOK NVARCHAR(30),
	@P_CD_CON NVARCHAR(3),
	@P_AM_CRD_1 NUMERIC(17,4),
	@P_DC_SETTLE NVARCHAR(50),
	@P_DT_CLOSE NVARCHAR(8),
	@P_DC_RMK NVARCHAR(400),
	@P_ID_INSERT NVARCHAR(15),
	@P_DTS_INSERT NVARCHAR(14)
)
AS
	SET @P_DTS_INSERT = GETDATE();
  UPDATE WEB_RM_OJT_PARTNER
  SET LN_PARTNER = @P_LN_PARTNER,
			FG_PARTNER = @P_FG_PARTNER,
			TP_INTOVER = @P_TP_INTOVER,
			TP_TRNSITION = @P_TP_INTOVER,
			NM_PRES = @P_NM_PRES,
			NO_COMPANY = @P_NO_COMPANY,
			NO_CORP = @P_NO_CORP,
			CD_PARTNER = @P_CD_PARTNER,
			NO_TEL = @P_NO_TEL,
			NO_FAX = @P_NO_FAX,
			TP_PRIO = @P_TP_PRIO,
			NO_POST1 = @P_NO_POST1,
			URL_PARTNER = @P_URL_PARTNER,
			EMAIL = @P_EMAIL,
			DC_ADS1_H = @P_DC_ADS1_H,
			DC_ADS1_D = @P_DC_ADS1_D,
			TP_JOB = @P_TP_JOB,
			DC_MAINGOODS = @P_DC_MAINGOODS,
			CLS_JOB = @P_CLS_JOB,
			CD_BANK = @P_CD_BANK,
			NO_PASSBOOK = @P_NO_PASSBOOK,
			CD_CON = @P_CD_CON,
			AM_CRD_1 = @P_AM_CRD_1,
			DC_SETTLE = @P_DC_SETTLE,
			DT_CLOSE = @P_DT_CLOSE,
			DC_RMK = @P_DC_RMK,
			ID_INSERT = @P_ID_INSERT,
			DTS_INSERT = @P_DTS_INSERT
  WHERE CD_COMPANY = @P_CD_COMPANY AND NO_PARTNER = @P_NO_PARTNER
GO
