SELECT IMCD.COMPANY_CD, -- 회사코드
       IMCD.INVTRX_DOC_NO, -- 생산출고수불번호
       IMCD.INVTRX_DOC_SQ, -- 생산출고수부번호 순번
       MAX(IMCD.PLANT_CD) PLANT_CD, -- 공장코드
       MAX(MPTM.PLANT_NM) PLANT_NM, -- 공장
       MAX(IMCD.INVTRX_DT) INVTRX_DT, -- 출고일
       MAX(IMCD.SL_CD) SL_CD, -- 저장위치코드
       MAX(MSLI.SL_NM) SL_NM, -- 저장위치
       MAX(IMCD.INVTRX_TP_CD) INVTRX_TP_CD, -- 수불유형코드
       MAX(MMEM.INVTRX_TP_NM) INVTRX_TP_NM, -- 수불유형
       MAX(PPDM.ITEM_CD) ITEM_CD, -- 생산지시품목
       CASE WHEN MAX(CIGS2.ITEM_NM) IS NOT NULL THEN MAX(CIGS2.ITEM_NM) ELSE MAX(CIM2.ITEM_NM) END ITEM_NM, -- 생산지시품목명
       MAX(IMCD.ITEM_CD) MTRIL_CD, -- 소요자재
       CASE WHEN MAX(CIGS.ITEM_NM) IS NOT NULL THEN MAX(CIGS.ITEM_NM) ELSE MAX(CIM.ITEM_NM) END MTRIL_NM, -- 소요자재명
       MAX(IMCD.ORD_UNIT_CD) ORD_UNIT_CD, -- 단위
       MAX(IMCL.LOT_NO) LOT_NO, -- 로트번호
       CASE WHEN MAX(IMCD.LOT_USE_YN) = 'Y' THEN MAX(IMCL.ORD_QT)*-1 ELSE MAX(IMCD.ORD_QT)*-1 END ORD_QT, -- 출고수량
       MAX(IMCD.STD_UNIT_CD) STD_UNIT_CD, -- 기준단위
       CASE WHEN MAX(IMCD.LOT_USE_YN) = 'Y' THEN MAX(IMCL.STD_UNIT_QT)*-1 ELSE MAX(IMCD.STD_UNIT_QT)*-1 END STD_UNIT_QT, --기준단위수량
       MAX(IMCD.ORD_NO) ORD_NO, -- 지시번호
       MAX(PPDM.PROD_TP_CD) PROD_TP_CD, -- 생산지시유형코드
       MAX(PTDM.PROD_TP_NM) PROD_TP_NM -- 생산지시유형
FROM IM_MTLDOC_DTL IMCD
       LEFT OUTER JOIN HR_EMP_MST HEM ON HEM.COMPANY_CD = IMCD.COMPANY_CD AND HEM.EMP_NO = IMCD.EMP_NO
       LEFT OUTER JOIN MA_DEPT_MST MDM ON MDM.COMPANY_CD = HEM.COMPANY_CD AND MDM.DEPT_CD = HEM.DEPT_CD AND TO_CHAR(SYSDATE,'YYYYMMDD')>= MDM.DEPT_START_DT
       LEFT OUTER JOIN CI_ITEM CIM ON CIM.ITEM_CD = IMCD.ITEM_CD
            INNER JOIN MA_ITEM MMIM ON MMIM.COMPANY_CD = IMCD.COMPANY_CD
                      AND MMIM.ITEM_CD = IMCD.ITEM_CD
            INNER JOIN MA_PITEM MMPM ON MMPM.COMPANY_CD = IMCD.COMPANY_CD
                      AND MMPM.ITEM_CD = IMCD.ITEM_CD
                      AND MMPM.PLANT_CD = IMCD.PLANT_CD
       LEFT OUTER JOIN CI_ITEMLANG_SDTL CIGS ON CIGS.ITEM_CD = IMCD.ITEM_CD AND CIGS.LANG_CD = 'KO'
       LEFT OUTER JOIN IM_MTLDOC_LOT IMCL ON IMCL.COMPANY_CD = IMCD.COMPANY_CD AND IMCL.INVTRX_DOC_NO = IMCD.INVTRX_DOC_NO AND IMCL.INVTRX_DOC_SQ = IMCD.INVTRX_DOC_SQ
       LEFT OUTER JOIN MA_CC_MST MCCM ON MCCM.COMPANY_CD = IMCD.COMPANY_CD AND MCCM.CC_CD = IMCD.CC_CD AND TO_CHAR(SYSDATE,'YYYYMMDD')>= MCCM.START_DT
       LEFT OUTER JOIN PP_PROD_MST PPDM ON PPDM.COMPANY_CD = IMCD.COMPANY_CD AND PPDM.PROD_NO = IMCD.ORD_NO AND PPDM.PROD_SQ = IMCD.ORD_SQ
            INNER JOIN MA_ITEM MIM ON MIM.COMPANY_CD = PPDM.COMPANY_CD
                      AND MIM.ITEM_CD = PPDM.ITEM_CD
            INNER JOIN MA_PITEM MPM ON MPM.COMPANY_CD = PPDM.COMPANY_CD
                      AND MPM.ITEM_CD = PPDM.ITEM_CD
                      AND MPM.PLANT_CD = PPDM.PLANT_CD
       LEFT OUTER JOIN PP_TPPRDORD_MST PTDM ON PTDM.COMPANY_CD = PPDM.COMPANY_CD AND PTDM.PROD_TP_CD = PPDM.PROD_TP_CD
       LEFT OUTER JOIN PP_PRODV_MST PPVM ON PPVM.COMPANY_CD = PPDM.COMPANY_CD AND PPVM.PLANT_CD = PPDM.PLANT_CD AND PPVM.PR_VER_CD = PPDM.PR_VER_CD
       LEFT OUTER JOIN MA_CODEDTL PP_P00230 ON PP_P00230.COMPANY_CD = PPVM.COMPANY_CD AND PP_P00230.MODULE_CD='PP' AND PP_P00230.FIELD_CD='P00230' AND PP_P00230.SYSDEF_CD=PPVM.PRPOS_CD
       LEFT OUTER JOIN MA_PLANT_MST MPTM ON MPTM.COMPANY_CD = IMCD.COMPANY_CD AND MPTM.PLANT_CD = IMCD.PLANT_CD
       LEFT OUTER JOIN MA_SL_INFO MSLI ON MSLI.COMPANY_CD = IMCD.COMPANY_CD AND MSLI.PLANT_CD = IMCD.PLANT_CD AND MSLI.SL_CD = IMCD.SL_CD
       LEFT OUTER JOIN MA_MOVETYPE_MST MMEM ON MMEM.COMPANY_CD = IMCD.COMPANY_CD AND MMEM.INVTRX_TP_CD = IMCD.INVTRX_TP_CD
       LEFT OUTER JOIN PP_PRODCONF_MST PPFM ON PPFM.COMPANY_CD = IMCD.COMPANY_CD AND PPFM.PRWK_NO = IMCD.PRWK_NO AND PPFM.PRWK_SQ = IMCD.PRWK_SQ
       LEFT OUTER JOIN CO_ADOCU_MST CAUM ON CAUM.COMPANY_CD = IMCD.COMPANY_CD AND CAUM.DOCU_NO = IMCD.COST_DOCU_NO
       LEFT OUTER JOIN CI_ITEM CIM2 ON CIM2.ITEM_CD = PPDM.ITEM_CD
       LEFT OUTER JOIN CI_ITEMLANG_SDTL CIGS2 ON CIGS2.ITEM_CD = PPDM.ITEM_CD AND CIGS2.LANG_CD = 'KO'
       LEFT OUTER JOIN MA_PROJECT_MST MPJM ON MPJM.COMPANY_CD = PPDM.COMPANY_CD AND MPJM.PJT_NO = PPDM.PJT_NO
       LEFT OUTER JOIN PS_WBS_MST PWM ON PWM.COMPANY_CD = PPDM.COMPANY_CD AND PWM.PJT_NO = PPDM.PJT_NO AND PWM.WBS_NO = PPDM.WBS_NO
WHERE IMCD.COMPANY_CD = #{company_cd}
    AND IMCD.PLANT_CD = #{plant_cd}
    AND ( IMCD.INVTRX_DT >= '20200901' AND IMCD.INVTRX_DT  <=  '20200921' )
    AND IMCD.INVTRX_DOC_NO LIKE '%' ||  #{invtrx_doc_no} || '%'
    AND IMCD.SL_CD LIKE '%' ||  #{sl_cd} || '%'
    AND IMCD.INVTRX_TP_CD = '321'
GROUP BY IMCD.COMPANY_CD , IMCD.INVTRX_DOC_NO , IMCD.INVTRX_DOC_SQ
ORDER BY MAX(IMCD.INVTRX_DT) , IMCD.INVTRX_DOC_NO , IMCD.INVTRX_DOC_SQ
