SELECT SGD.GIDOC_NO, -- 판매출고수불번호
       SGD.GIDOC_SQ, -- 판매출고수불번호순
       SGD.INVTRX_DT, -- 판매출고일
       SGD.PLANT_CD, -- 공장코드
       MPM.PLANT_NM, -- 공장명
       SGD.SL_CD, -- 저장위치코드
       MSI.SL_NM, -- 저장위치명
       SGD.ITEM_CD, -- 품목코드
       CI.ITEM_NM, -- 품목명
       SGD.ORD_QT, -- 판매출고수량
       SGD.ORD_UNIT_CD, -- 판매단위
       SGD.INVTRX_TP_CD, -- 수불유형코드
	     SGD.DLVDOC_NO, -- 납품지시번호
	     SGD.DLVDOC_SQ, -- 납품지시번호순
	     SDM.DO_DT, -- 납품지시일
       SDD.DLVPRTN_CD, -- 납품처코드
       CPM.PARTNER_NM AS DLVPRTN_NM, -- 납품처명
       IMCS.SRC_DOC_NO -- 생산입고번호
FROM SD_GI_DTL SGD
		LEFT OUTER JOIN SD_DLV_DTL SDD ON SDD.COMPANY_CD = SGD.COMPANY_CD AND SDD.DLVDOC_NO = SGD.DLVDOC_NO AND SDD.DLV_SQ = SGD.DLVDOC_SQ
		LEFT OUTER JOIN SD_DLV_MST SDM ON SDM.COMPANY_CD = SGD.COMPANY_CD AND SDM.DLVDOC_NO  = SGD.DLVDOC_NO
		LEFT OUTER JOIN CI_PARTNER_MST CPM ON CPM.PARTNER_CD = SDD.DLVPRTN_CD
		LEFT OUTER JOIN MA_PLANT_MST MPM ON MPM.COMPANY_CD = SGD.COMPANY_CD AND MPM.PLANT_CD = SGD.PLANT_CD
    LEFT OUTER JOIN MA_SL_INFO MSI ON MSI.COMPANY_CD = SGD.COMPANY_CD AND MSI.PLANT_CD = SGD.PLANT_CD AND MSI.SL_CD = SGD.SL_CD
    LEFT OUTER JOIN CI_ITEM CI ON SGD.ITEM_CD = CI.ITEM_CD
    LEFT OUTER JOIN IM_MTLDOC_SDTL_X10029 IMCS ON SGD.COMPANY_CD = IMCS.COMPANY_CD AND SGD.PLANT_CD = IMCS.PLANT_CD AND SGD.INVTRX_DOC_NO = IMCS.INVTRX_DOC_NO AND SGD.INVTRX_DOC_SQ = IMCS.INVTRX_DOC_SQ AND SGD.INVTRX_TP_CD = IMCS.INVTRX_TP_CD
