SELECT IMCD.COMPANY_CD,
		       IMCD.INVTRX_DOC_NO,
		       IMCD.INVTRX_DOC_SQ,
		       IMCD.PLANT_CD,
		       MPTM.PLANT_NM,
		       IMCD.INVTRX_DT,
		       IMCD.SL_CD,
		       MSLI.SL_NM,
		       IMCD.ITEM_CD AS MTRIL_CD,
		       CIM.ITEM_NM AS MTRIL_NM,
		       CIM.ITEM_CD,
		       CIM.ITEM_NM,
		       IMCD.ORD_UNIT_CD,
		       IMCL.LOT_NO,
		       IMCD.LOT_USE_YN,
		       IMCD.ORD_QT,
		       IMCD.ORD_NO,
		       PPDM.PROD_TP_CD,
		       PTDM.PROD_TP_NM,
		       PPDM.STD_UNIT_CD,
		       IMCD.INVTRX_TP_CD,
		       PPDM.PROD_QT,
		       IMCS.SRC_DOC_NO
		FROM   @{dzparam_dbname}IM_MTLDOC_DTL IMCD
			LEFT OUTER JOIN MA_PLANT_MST MPTM ON MPTM.COMPANY_CD = IMCD.COMPANY_CD AND MPTM.PLANT_CD = IMCD.PLANT_CD
			LEFT OUTER JOIN MA_SL_INFO MSLI ON MSLI.COMPANY_CD = IMCD.COMPANY_CD AND MSLI.PLANT_CD = IMCD.PLANT_CD AND MSLI.SL_CD = IMCD.SL_CD
			LEFT OUTER JOIN PP_PROD_MST PPDM ON PPDM.COMPANY_CD = IMCD.COMPANY_CD AND PPDM.PROD_NO = IMCD.ORD_NO AND PPDM.PROD_SQ = IMCD.ORD_SQ
			LEFT OUTER JOIN CI_ITEM CIM ON CIM.ITEM_CD = IMCD.ITEM_CD
			LEFT OUTER JOIN IM_MTLDOC_LOT IMCL ON IMCL.COMPANY_CD = IMCD.COMPANY_CD AND IMCL.INVTRX_DOC_NO = IMCD.INVTRX_DOC_NO AND IMCL.INVTRX_DOC_SQ = IMCD.INVTRX_DOC_SQ
			LEFT OUTER JOIN PP_TPPRDORD_MST PTDM ON PTDM.COMPANY_CD = PPDM.COMPANY_CD AND PTDM.PROD_TP_CD = PPDM.PROD_TP_CD
			LEFT OUTER JOIN IM_MTLDOC_SDTL_X10029 IMCS ON IMCD.COMPANY_CD = IMCS.COMPANY_CD AND IMCD.PLANT_CD = IMCS.PLANT_CD AND IMCD.INVTRX_DOC_NO = IMCS.INVTRX_DOC_NO AND IMCD.INVTRX_DOC_SQ = IMCS.INVTRX_DOC_SQ AND IMCD.INVTRX_TP_CD = IMCS.INVTRX_TP_CD
		WHERE   IMCD.COMPANY_CD = #{company_cd}
 			AND IMCD.PLANT_CD = #{plant_cd}
			AND IMCD.INVTRX_DT BETWEEN #{invtrx_sdt} AND #{invtrx_edt}
			AND IMCD.INVTRX_TP_CD = '321'
