CREATE TABLE WEB_RM_CM_YBTOUR_SALES_OPT_ATTACHFILE
(
  CD_COMPANY NVARCHAR(10) NOT NULL,
  NO_PARTNER INT NOT NULL,
  NO_OPT_FILE INT NOT NULL,
  NM_FILE NVARCHAR(100),
  URL_FILE NVARCHAR(100),
  SZ_FILE NVARCHAR(30),
  ID_FILE_UPLOAD NVARCHAR(15),
  DTS_FILE_UPLOAD NVARCHAR(14),
  DC_REMARK NVARCHAR(100),
  ID_INSERT NVARCHAR(15),
  DTS_INSERT NVARCHAR(14),
  ID_UPDATE NVARCHAR(15),
  DTS_UPDATE NVARCHAR(14)

  PRIMARY KEY(CD_COMPANY, NO_PARTNER, NO_OPT_FILE)
)
