ALTER PROCEDURE [NEOE].[UP_WHR_CM_HELLO_WORLD_S]
    @P_KEYWORD NVARCHAR(10)
AS
    SELECT CD_COMPANY, NO_PARTNER, NO_CUST, NO_CELPHONE FROM WEB_RM_OJT_CUSTOMER WHERE CD_COMPANY = @P_KEYWORD
GO

ALTER PROCEDURE [NEOE].[UP_WHR_CM_HELLO_WORLD_B]
AS
  SELECT c.NM_CUST, c.NO_PARTNER, p.LN_PARTNER
  FROM WEB_RM_OJT_CUSTOMER AS c
  LEFT JOIN WEB_RM_OJT_PARTNER AS p
  ON c.NO_PARTNER = p.NO_PARTNER
GO

ALTER PROCEDURE [NEOE].[UP_WHR_CM_HELLO_WORLD_D]
    @P_NO_PARTNER INT(4)
AS
    SELECT LN_PARTNER, FG_PARTNER, TP_TRNSITION, NO_COMPANY, NO_CORP, NM_PRES, EMAIL, URL_PARTNER, NO_TEL, NO_FAX, NO_POST1, DC_ADS1_H, DC_ADS1_D, TP_JOB, CLS_JOB, DC_MAINGOODS
    FROM WEB_RM_OJT_PARTNER
    WHERE NO_PARTNER = @P_NO_PARTNER
GO

ALTER PROCEDURE [NEOE].[UP_WHR_CM_HELLO_WORLD_D2]
    @P_NO_PARTNER INT
AS
  SELECT c.CD_COMPANY, c.NO_CUST, c.NM_CUST, c.NO_PARTNER, p.LN_PARTNER, c.NO_TEL, c.DT_BIRYYMM
  FROM WEB_RM_OJT_CUSTOMER AS c
  LEFT JOIN WEB_RM_OJT_PARTNER AS p
  ON c.NO_PARTNER = p.NO_PARTNER
  WHERE c.NO_PARTNER = @P_NO_PARTNER
GO

**DB 참고
SELECT * FROM MA_CODEDTL WHERE CD_COMPANY = 'ASDC' AND CD_FIELD = 'MA_B000043';
//은행명
SELECT * FROM MA_EMP WHERE CD_COMPANY = 'YBTOUR' AND  NO_EMP= 'DOUZONE';
//회사코드
SELECT * FROM MA_USER WHERE CD_COMPANY ='YBTOUR' AND ID_USER = 'DOUZONE';
// 로그인 정보


this.select(this.rows('tr:first'));
exec sp_helptext UP_WHR_CM_HELLO_WORLD_I
exec sp_helptext UP_WHR_CM_HELLO_WORLD_U2
exec sp_helptext UP_WHR_CM_HELLO_WORLD_M2 // 프로시저 조회

select * from WEB_RM_OJT_CUSTOMER
select * from WEB_RM_OJT_PARTNER

DELETE FROM WEB_RM_OJT_CUSTOMER WHERE NO_PARTNER = 3
ALTER TABLE WEB_RM_OJT_CUSTOMER ADD DT_BIRYYMM NVARCHAR(8) // 테이블 컬럼 추가

UPDATE WEB_RM_OJT_CUSTOMER
SET DT_BIRYYMM = 920603
WHERE NM_CUST = 'D1'

ALTER PROCEDURE [NEOE].[UP_WHR_CM_HELLO_WORLD_U2]
(
    @P_CD_COMPANY NVARCHAR(10),
    @P_NO_PARTNER INT,
    @P_NO_CUST INT,
    @P_NO_TEL NVARCHAR(20),
    @P_DT_BIRYYMM NVARCHAR(8)
)
AS
  UPDATE WEB_RM_OJT_CUSTOMER
  SET NO_TEL = @P_NO_TEL, DT_BIRYYMM = @P_DT_BIRYYMM
  WHERE CD_COMPANY = @P_CD_COMPANY AND NO_PARTNER = @P_NO_PARTNER AND NO_CUST = @P_NO_CUST
GO

ALTER PROCEDURE [NEOE].[UP_WHR_CM_HELLO_WORLD_DEL]
(
	@P_CD_COMPANY NVARCHAR(10),
	@P_NO_PARTNER INT,
	@P_NM_CUST NVARCHAR(20),
	@P_NO_TEL NVARCHAR(20),
	@P_DT_BIRYYMM NVARCHAR(8)
)
AS
  DELETE FROM WEB_RM_OJT_CUSTOMER
  WHERE CD_COMPANY = @P_CD_COMPANY AND NO_PARTNER = @P_NO_PARTNER AND NM_CUST = @P_NM_CUST
GO


그리드 컬럼 히든(숨김처리)->NO_PARTNER -> DB로 넘겨 파트너 테이블에서 NO_PARTNER where조건절에 넣어서 한줄만 밑에(디테일) 출력

CD_COMPANY// 회사코드
NO_PARTNER // 고객번호
NO_CUST // 담당자번호
NO_CELPHONE // 핸드폰번호


마스터 - WEB_RM_OJT_PARTNER
디테일 - WEB_RM_OJT_CUSTOMER
1:N -> WEB_RM_OJT_PARTNER : WEB_RM_OJT_CUSTOMER



http://localhost:8090/p_whr_cm_ojt_hello_world

디테일을 기준으로 마스터를 조인 key => NO_PARTNER
LN_PARTNER // 고객명
NM_CUST // 담당자명


FG_PARTNER // 고객구분
TP_TRNSITION // 거래관계
NO_COMPANY // 사업자번호
NO_CORP // 법인등록번호
NM_PRES // 대표이사
EMAIL // 대표이메일
URL_PARTNER // 홈페이지
NO_TEL // 전화번호
NO_FAX // FAX번호
NO_POST1 // 우편번호
DC_ADS1_H // 주소
DC_ADS1_D // 상세주소
TP_JOB // 업태
CLS_JOB // 종목
DC_MAINGOODS // 주생산
