ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_CUSTOMER_ALL_D]
(
  @P_CD_COMPANY NVARCHAR(10),
  @P_NO_PARTNER INT,
  @P_ID_DELETE  NVARCHAR(15)
)
AS

BEGIN

  SET NOCOUNT ON;
  DECLARE @V_ERR_MSG NVARCHAR(255) --에러메시지

  IF ( RTRIM(ISNULL(@P_CD_COMPANY, '')) = '' )
  BEGIN
    SET @V_ERR_MSG = N'회사코드는 필수입니다.';
    GOTO ERROR
  END;

  IF ( ISNULL(@P_NO_PARTNER, '') = '' )
  BEGIN
    SET @V_ERR_MSG = N'거래처코드는 필수입니다.';
    GOTO ERROR
  END;

  BEGIN TRANSACTION

-- 한 고객에 대한 연락처 데이터 삭제
  DELETE FROM WEB_RM_OJT_CUSTOMER
   WHERE CD_COMPANY = @P_CD_COMPANY
     AND NO_PARTNER = @P_NO_PARTNER;

  IF ( @@ERROR <> 0 )
  BEGIN
    ROLLBACK TRANSACTION;
    RETURN;
  END

  COMMIT TRANSACTION;

  RETURN

ERROR:
  RAISERROR( @V_ERR_MSG, 16, 1 )
  RETURN


END
