ALTER PROCEDURE [NEOE].[UP_WRM_CM_HELLO_WORLD_PARTNER_D]
(
  @P_CD_COMPANY NVARCHAR(7),
  @P_NO_PARTNER INT,
  @P_ID_DELETE  NVARCHAR(15)
)
AS
BEGIN

  SET NOCOUNT ON;

  DECLARE @V_ERR_MSG NVARCHAR(255) --에러메시지

  IF ( RTRIM(ISNULL(@P_CD_COMPANY, '')) = '' )
  BEGIN
    SET @V_ERR_MSG = N'회사코드는 필수입니다.';
    GOTO ERROR
  END;

  IF ( ISNULL(@P_NO_PARTNER, '') = '' )
  BEGIN
    SET @V_ERR_MSG = N'거래처코드는 필수입니다.';
    GOTO ERROR
  END;

  BEGIN TRANSACTION


  DELETE WEB_RM_OJT_PARTNER
   WHERE CD_COMPANY = @P_CD_COMPANY
     AND NO_PARTNER = @P_NO_PARTNER;

  IF ( @@ERROR <> 0 )
  BEGIN
    ROLLBACK TRANSACTION;
    RETURN;
  END

  COMMIT TRANSACTION;

  RETURN

ERROR:
  RAISERROR( @V_ERR_MSG, 16, 1 )
  RETURN

END
