USE [NEOE]
GO
/****** Object:  StoredProcedure [NEOE].[UP_WRM_CM_CUDO_CDPIPE_ENDED_S1]    Script Date: 2020-08-31 오전 11:01:04 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [NEOE].[UP_WRM_CM_CUDO_CDPIPE_ENDED_S1]
	@I_START_DT_SRCH	NCHAR(8),		--조회일자
	@I_END_DT_SRCH	  NCHAR(8),		--조회일자
	@P_USER_ID			  NVARCHAR(50),
	@I_OP_DPMT				NVARCHAR(100),	--기회부서
	@I_CD_DEPT		    NVARCHAR(100),	--기회부서
	@CD_COMPANY				NVARCHAR(10),
	@P_PAGE			      INT,
	@P_LIST_SIZE	    INT
AS

-- =============================================
-- Author:		황현욱
-- Create date: 20180116
-- Description: 마감된 영업기회 현황
-- =============================================
/* *********************************************************
** Change History
** 2018/04/17 | LMG     | 권한별 기회부서 조회는 파라메터로 받아서 조회하도록 수정(+구분자로 넘어옴)
*********************************************************** */
BEGIN

  SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

  SET NOCOUNT ON;
	IF (@P_PAGE = 0 OR @P_PAGE IS NULL)
	BEGIN
		SET @P_PAGE = 1
	END
	DECLARE @V_LISTCOUNT INT

	SET @V_LISTCOUNT = @P_LIST_SIZE

  BEGIN TRY
			 SELECT H.* FROM (
			 SELECT ROW_NUMBER() OVER(ORDER BY MV.NO_OPT ASC) ROWID,
			 		CD_COMPANY,
					NO_OPT,
					NM_THEMA,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00001' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.ST_SALESTAGE AND B.USE_YN = 'Y') AS ST_SALESTAGE,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00002' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.TP_PRIO AND B.USE_YN = 'Y') AS TP_PRIO,
					ST_PMSTRANS,
					DT_PMSTRANS,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00003' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY= @CD_COMPANY AND B.CD_SYSDEF = MV.ST_PROGRESS AND B.USE_YN = 'Y') AS ST_PROGRESS,
					DT_OPPR,
					DT_ESTCLOSE,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00004' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.DC_OPPATH AND B.USE_YN = 'Y') AS DC_OPPATH,
					RT_ESTSALE,
					(SELECT EMP.NM_KOR + '('+ EMP.NM_ENG + ')' FROM MA_EMP AS EMP WHERE EMP.CD_COMPANY = MV.CD_COMPANY AND EMP.NO_EMP =MV.NO_OPPR_EMPID ) NO_OPPR_EMPID,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00005' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_PIPE AND B.USE_YN = 'Y') AS CD_PIPE,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00006' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_OPTYPE AND B.USE_YN = 'Y') AS CD_OPTYPE,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00007' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_OPCATEGORI AND B.USE_YN = 'Y') AS CD_OPCATEGORI,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00008' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_OPPR AND B.USE_YN = 'Y') AS CD_OPPR,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00009' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_DOMES AND B.USE_YN = 'Y') AS CD_DOMES,
					NO_REFOPT,
					(SELECT A.LN_PARTNER FROM WEB_RM_CM_CUDO_PARTNER A  WHERE A.CD_COMPANY = @CD_COMPANY AND A.NO_PARTNER = MV.NO_PARTNER) AS NO_PARTNER,
					NO_ENDUSER,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00010' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_PRIORITY AND B.USE_YN = 'Y') AS CD_PRIORITY,
					DT_FNSCLOSE,
					ISNULL(AM_ESTSALE,0) AM_ESTSALE,
					ISNULL(AM_MARGIN,0) AM_MARGIN,
					ISNULL(RT_MARGIN,0) RT_MARGIN,
					AM_FOREG,
					CD_FOREG,
					RM_FOREG,
					DC_REMARK,
					ID_INSERT,
					DTS_INSERT,
					ID_UPDATE,
					DTS_UPDATE,
					DUMMY_STR_01,
					DUMMY_STR_02,
					DUMMY_STR_03,
					DUMMY_STR_04,
					DUMMY_STR_05,
					(SELECT B.NM_SYSDEF FROM MA_CODE A  INNER JOIN MA_CODEDTL B ON A.CD_FIELD = B.CD_FIELD WHERE A.CD_FIELD = 'CZ_RM00011' AND A.CD_COMPANY = B.CD_COMPANY AND B.CD_COMPANY = @CD_COMPANY AND B.CD_SYSDEF = MV.CD_PRIORITY AND B.USE_YN = 'Y') AS CD_PRIORITY1,
					DC_LOSE_CLOSE,
					DT_PJT_PLAN_ST,
					DT_PJT_PLAN_ED
			 FROM WEB_RM_CM_CUDO_SALES_OPPORTUNITY MV
			 WHERE 1 = 1
				 AND MV.CD_COMPANY = @CD_COMPANY
				 AND MV.DT_FNSCLOSE BETWEEN SUBSTRING(@I_START_DT_SRCH,1,4)+'-'+SUBSTRING(@I_START_DT_SRCH,5,2)+'-'+SUBSTRING(@I_START_DT_SRCH,7,2) AND SUBSTRING(@I_END_DT_SRCH,1,4)+'-'+SUBSTRING(@I_END_DT_SRCH,5,2)+'-'+SUBSTRING(@I_END_DT_SRCH,7,2)
				 AND ( MV.CD_PIPE = '004')
				 --AND MV.CD_OPPR   IN (SELECT VAL1 FROM FN_CZ_SPLIT(@I_OP_DPMT,'+'))
				 AND (ISNULL(@I_OP_DPMT,'')='' OR MV.CD_OPPR = @I_OP_DPMT)
				 AND (ISNULL(@I_CD_DEPT,'')='' OR MV.SALE_DEPT = @I_CD_DEPT)
			 ) H
			 WHERE H.ROWID <= @P_PAGE * @V_LISTCOUNT AND (@P_PAGE = 1 OR H.ROWID > (@P_PAGE-1) * @V_LISTCOUNT)
			 ORDER BY H.ROWID ASC

  END TRY

	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000);
		DECLARE @ErrorSeverity INT;
		DECLARE @ErrorState INT;

		SELECT
				@ErrorMessage = ERROR_MESSAGE(),
				@ErrorSeverity = ERROR_SEVERITY(),
				@ErrorState = ERROR_STATE();

		RAISERROR ( @ErrorMessage, @ErrorSeverity, @ErrorState );

	END CATCH

END
